Return the connection interface get function.

diff --git a/winbind-dnsupdate b/winbind-dnsupdate
--- a/winbind-dnsupdate
+++ b/winbind-dnsupdate
@@ -214,6 +214,36 @@ get_dc_hostname() {
     return $ret
 }
 
+get_connection_iface_to_ldap() {
+    local dc_hostname=
+    local dc_ip=
+    local connect_iface=
+    local out=
+    local ret=1
+
+    # Get actual dc connection ip
+    if dc_hostname="$(get_dc_hostname)"; then
+        if ! dc_ip="$(get_ip_from_hostname $dc_hostname)"; then
+            log_warning "Can not resolve domain controller address for $dc_hostname"
+        fi
+    else
+        log_warning "Can not get domain controller hostname"
+    fi
+
+    # Find iface
+    if out="$(ip route get dport 389 "$dc_ip")"; then
+        if connect_iface="$(awk -F'dev ' 'NR==1 {print $2}' <<< $out | awk '{print $1}' 2>&1)"; then
+            echo -n "$connect_iface" && ret=0
+        else
+            log_warning "Can not parse connection interface"
+            log_warning "AWK errror: $connect_iface"
+        fi
+    else
+        log_warning "Ip route error: $out"
+    fi
+    return $ret
+}
+
 get_old_ipv4_addr() {
     local hostname="$1"
     local ret=0
